sudo: false

language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  allow_failures:
    - python: "2.6"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  fast_finish: true

install:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pip install -r requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install six networkx==1.9.1; fi
  - pip install -r testing-requirements.txt
  - pip install -r docs-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 3.4 && $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install enum34; fi

script:
  - echo "Checking correctness:"
  - nosetests
  - echo "Checking PEP 8 compliance:"
  - flake8 .
  - echo "Checking PEP 257 compliance:"
  - pep257 .
  - echo "Checking that the docs build:"
  - sphinx-build -E docs docs/_build

after_success:
  - coveralls
