sudo: false

language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  allow_failures:
    - python: "2.6"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  fast_finish: true

install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib; fi
  - pip install -r testing-requirements.txt
  - pip install -r docs-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 3.4 && $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install enum34; fi

script:
  - nosetests
  - flake8 .
  - pep257 .
  - sphinx-build -E docs docs/_build

after_success:
  - codecov
