sudo: false

language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  allow_failures:
    - python: "2.6"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  fast_finish: true

install:
  - pip install -q -r requirements.txt

script:
  - nosetests --with-doctest --with-coverage --cover-package=CAOS
  - flake8 .

after_success:
  - coveralls